name: Docs building

on:
  schedule:
    - cron: "0 0 * * SUN"
  workflow_dispatch:


# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Install deps
        run: |
          sudo apt-get -y install \
            intltool \
            doxygen \
            graphviz;
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v2
      - name: Build docs
        env:
          SRC_DIR: ${{ github.workspace }}
          BUILD_DIR: ${{ github.workspace }}/build
        run: |
          doxygen doc/Doxyfile
      - name: Upload page artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: doc/html
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
